spring:
  application:
    name: catalog-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: true
      retry:
        max-attempts: 5
        initial-interval: 1000
        max-interval: 2000
        multiplier: 2
      enabled: false
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5433/polar_db_catalog
    hikari:
      connection-timeout: 2000 #ms
      maximum-pool-size: 5

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

server:
  port: 8081
  tomcat:
    threads:
      max: 20
      min-spare: 5
management:
  endpoints:
    web:
      exposure:
        include: "*"
flyway:
  url: jdbc:postgresql://localhost:5433
  schemas: polar_db_catalog
  user: postgres
  password: postgres
learning:
  backend:
    languages: Java, Python, Go