spring:
  application:
    name: catalog-service
server:
  port: 8081
  tomcat:
    threads:
      max: 20
      min-spare: 5

polar:
  greeting: Welcome to the local Book catalog
learning:
  backend:
    languages: Java, Python, Go