spring:
  application:
    name: catalog-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: true
      retry:
        max-attempts: 5
        initial-interval: 1000
        max-interval: 2000
        multiplier: 2
server:
  port: 8081
  tomcat:
    threads:
      max: 20
      min-spare: 5
management:
  endpoints:
    web:
      exposure:
        include: "*"
learning:
  backend:
    languages: Java, Python, Go