apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  labels:
    app: catalog-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8081"
    spec:
      containers:
        - name: catalog-service
          image: ghcr.io/fofanaabou/catalog-service:latest
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command:
                  - "sh"
                  - "-c"
                  - "sleeep"
          ports:
            - containerPort: 8081
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: SPRING_PROFILES_ACTIVE
              value: test-data,prod
          volumeMounts:
            - name: catalog-config-volume
              mountPath: /workspace/config
          livenessProbe:
            httpGet:
              port: 8081
              path: /actuator/health/liveness
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: 8081
              path: /actuator/health/liveness
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: catalog-config-volume
          configMap:
            name: catalog-config
      imagePullSecrets:
        - name: registry-secret