apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  labels:
    app: catalog-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalog-api
  template:
    metadata:
      name: catalog-api
      labels:
        app: catalog-api
    spec:
      containers:
        - name: catalog-service
          image: fofanaabou/catalog-service:latest
          ports:
            - containerPort: 8080

